### ISSUE TITLE
Add option to allow councils to download Right of Reply responses

### ISSUE THREAD

**Issue by struan** [mysociety/ceuk-marking#77]
> Councils who respond who log into GRACE for the Right of Reply to be able to download a copy of the first mark notes and the Right of Reply notes they have made.
> - Clearer submit button for the Right of Reply, rather than just the “Save” but a full “submit” button. So might need to have a “save” and “submit and download” button with a landing page that then says “your Right of Reply has been submitted.”

**Comment by zarino** [comment]
From Annie:

> We're going to be doing the Right of Reply briefing call on 20th October. So it would be good to know by then how/if councils will be able to download a copy of their RoR response. Then the RoR is opening on 11th Nov.

**Comment by zarino** [comment]
Since RoR users will have to review multiple sections (each presented on their own form page), we’re thinking that the "download" button should be on the main section list page they first see – and that it should be greyed out until they’ve responded yes/no to all of the questions in all of the sections.
